- name: Let's Install ElasticSearch
  hosts: elastic
  gather_facts: False
  become: true
  become_method: sudo
  become_user: ubuntu

  tasks:

    - name: update ubuntu
      shell:
        sudo apt update -y
        
    - name: update ubuntu
      shell:
        sudo apt update -y
        
    - name: Install the dependencies necessary to add a new HTTPS repository
      shell:
        sudo apt install apt-transport-https ca-certificates wget -y

    - name: Import the repositoryâ€™s GPG key
      shell:        
        wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -

    - name: add the Elasticsearch repository to the system
      shell:
        sudo sh -c 'echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" > /etc/apt/sources.list.d/elastic-7.x.list' 
        
        
    - name: install Elasticsearch
      shell:
        sudo apt install elasticsearch -y
        
    - name: Daemon reload
      shell:        
        sudo systemctl daemon-reload

    - name: add the Elasticsearch repository to the system
      shell:
        sudo systemctl enable elasticsearch
        
        
    - name: Start Elasticsearch
      shell:
        sudo systemctl start elasticsearch      
        
        
    - name: Status of Elasticsearch
      shell:
        sudo systemctl status elasticsearch           

    - name: curl to send an HTTP request to port 9200 on localhost
      shell:        
        curl -X GET "localhost:9200/"

    - name: view the messages logged by the Elasticsearch service
      shell:
        sudo journalctl -u elasticsearch

    - name: Add in inventory file
      lineinfile:
        path: /etc/ansible/hosts
        insertafter: '^\[hosts1\]'
        line: "[elastic]"
        state: present